import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { action, ...params } = body;

    switch (action) {
      case 'text_summarize':
        return handleTextSummarize(params);
      case 'question_answer':
        return handleQuestionAnswer(params);
      case 'text_classify':
        return handleTextClassify(params);
      default:
        return NextResponse.json(
          { error: 'Unknown action', success: false },
          { status: 400 }
        );
    }
  } catch (error) {
    console.error('Error in LangChain API:', error);
    return NextResponse.json(
      { error: 'LangChain service error', success: false },
      { status: 500 }
    );
  }
}

async function handleTextSummarize(params: any) {
  const { text, max_length = 100 } = params;
  
  // Mock text summarization - in production, this would use actual LangChain/OpenAI
  const mockSummary = text.length > max_length 
    ? text.substring(0, max_length) + '...'
    : text;
    
  return NextResponse.json({
    summary: mockSummary,
    success: true,
    timestamp: new Date().toISOString()
  });
}

async function handleQuestionAnswer(params: any) {
  const { question, context } = params;
  
  // Mock Q&A - in production, this would use actual LangChain/OpenAI
  const mockAnswer = `Based on the context provided, here's a response to "${question}": This is a mock answer generated by the integrated MCP service.`;
  
  return NextResponse.json({
    answer: mockAnswer,
    success: true,
    timestamp: new Date().toISOString()
  });
}

async function handleTextClassify(params: any) {
  const { text, categories } = params;
  
  // Mock classification - in production, this would use actual LangChain/OpenAI
  const mockCategory = categories && categories.length > 0 
    ? categories[0] 
    : 'general';
    
  return NextResponse.json({
    category: mockCategory,
    confidence: 0.85,
    success: true,
    timestamp: new Date().toISOString()
  });
}
